### ISSUE TITLE
Implement FSWATCHER_PATH_ENCODING_***

### ISSUE THREAD

**Issue by wc-duck** [wc-duck/fswatcher#1]
Macro currently do nothing!

**Comment by yanglinjie8823857** [comment]
just do it！

**Comment by wc-duck** [comment]
I'm open for pullrequests as I currently do not have that much time between work and family with small kids.

**Comment by wc-duck** [comment]
I have decided against this as it just makes the api harder to read and write + the potential define-mismatch issue in code using fswatcher. Also, me being an utf8 everywhere kind of guy would suggest just converting encoding at the border where you are talking to the system-api:s, read WinAPI.
Please re-open if any one have a good reason to do this anyways... im no worse than that I can change my mind ;)
