### ISSUE TITLE
Handling Symbolic Links

### ISSUE THREAD

**Issue by lundmark** [wc-duck/fswatcher#2]
It would be awesome if this tool could handle symbolic links and watch for changes inside those as well.

**Comment by wc-duck** [comment]
I'll see what I can do tonight when the kid is sleeping... Otherwise pull requests are always welcome ;)

**Comment by wc-duck** [comment]
Works on my linux-machine, but not on the autobuilders =/
I'll fix the autobuilder and then have a look at windows.

**Comment by wc-duck** [comment]
In windows I have to test hard-links, symbolic links and junctions and at least document how and if they work.

**Comment by wc-duck** [comment]
old
